#your sister went to the market to buy 3 items
print("Enter the first item")
firstitem=input()
print("first item price")
firstitemprice=float(input())
print("Enter the second item")
seconditem=input()
print("second item price")
seconditemprice=float(input())
print("Enter the third item")
thirditem=input()
print("third item price")
thirditemprice=float(input())
print("item details:" + firstitem + ":" + str(firstitemprice) + "," + seconditem + ":" + str(seconditemprice) + "," + thirditem + ":" + str(thirditemprice)) 